name: Publish

on:
  push:
    branches: main

jobs:
  publish:
    name: Publish container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the noalbs Docker image
        run: |
          docker build . --tag ghcr.io/gussy/noalbs:latest
          docker run ghcr.io/gussy/noalbs:latest
          docker push ghcr.io/gussy/noalbs:latest
